### PR TITLE
changing getLastTimeProduced to use UTC for current time to avoid tz …

### PR DESCRIPTION
**Pull request by ghoti143**
changing getLastTimeProduced to use UTC for current time to avoid tz offset issues.  also corrected some spelling mistakes.

### CODE REVIEW

**Comment by ghoti143** [comment]
Hmmm... seems like my fix didn’t quite work.  When checking from my iPad at home, the time zone offset doesn’t seem to work.  I’ll keep looking for a solution...

**Comment by eedsilva** [comment]
It works fine on my laptop, but on mobile looks weird.
I'll keep an eye open on this issue as well. 

Thanks.

**Comment by ghoti143** [comment]
Yes - very strange.  Same behavior on my end.  Doing datetime stuff client side is always fraught with these kinds of difficulties.  Any plans on doing this sort of stuff server side and using socket.io to push updated data down to client (similar to cryptolions testnet monitor)?  I could write up an issue and try taking a stab at if you'd like.

**Comment by ghoti143** [comment]
I figured out a way to resolve this.  https://github.com/Telos-Foundation/telos-monitor/pull/32

Thanks!
Mike

**Pull request merged**
